services:
  # Disable pgbouncer in simple local dev unless explicitly testing pooling
  pgbouncer:
    scale: 0

  db:
    ports:
      - "10000:5432"

  api:
    environment:
      NODE_ENV: development
      # Local dev: by default connect directly to the DB service. To test pooling
      # set DATABASE_URL to point at pgbouncer:6432 (eg. export DATABASE_URL=postgresql://postgres:postgres@pgbouncer:6432/sav3)
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5432/sav3}
      PORT: ${PORT:-4000}
      # If you want to test PgBouncer locally, set USE_PGBOUNCER=true in your .env
      # and ensure a local pgbouncer service is started in the compose override.
      USE_PGBOUNCER: ${USE_PGBOUNCER:-false}
    ports:
      - "10010:4000"
    volumes:
      - ./:/usr/src/app
    # command: sh -c "npm run dev"
