# ===========================================
# TRAEFIK CONFIGURATION FOR APHILA.IO
# ===========================================
# Static configuration for Traefik reverse proxy
# Handles SSL certificates, routing, and monitoring

global:
  checkNewVersion: false
  sendAnonymousUsage: false

# ===========================================
# API AND DASHBOARD
# ===========================================
api:
  dashboard: true
  debug: false
  insecure: false

# ===========================================
# ENTRY POINTS
# ===========================================
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        options: default

# ===========================================
# PROVIDERS
# ===========================================
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: sav3-network

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# ===========================================
# CERTIFICATE RESOLVERS (Let's Encrypt)
# ===========================================
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@aphila.io
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

  # Alternative DNS challenge (if needed)
  letsencrypt-dns:
    acme:
      email: admin@aphila.io
      storage: /letsencrypt/acme-dns.json
      dnsChallenge:
        provider: cloudflare # Change to your DNS provider
        delayBeforeCheck: 0

# ===========================================
# LOGGING
# ===========================================
log:
  level: INFO
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

# ===========================================
# METRICS (Prometheus)
# ===========================================
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

# ===========================================
# TRACING (Optional)
# ===========================================
# tracing:
#   jaeger:
#     samplingServerURL: "http://jaeger:14268/api/sampling"
#     localAgentHostPort: "jaeger:6831"

# ===========================================
# EXPERIMENTAL FEATURES
# ===========================================
experimental:
  plugins:
    cloudflarewarp:
      modulename: github.com/BetterCorp/cloudflarewarp
      version: v1.3.0
