name: Autopilot

on:
  schedule:
    - cron: "0 * * * *" # hourly
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Report failure
        if: failure()
        run: |
          gh issue create --title "Autopilot: CI build failure" --body "Scheduled autopilot build failed. Check actions run." --repo sevans717/aphila
